---
all:
  children:
    collectors:
      hosts:
        host1:
          ansible_host: 192.168.1.100
          ansible_user: volttron
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
#          venv_for_ansible: "{{ ansible_env.HOME }}/ansible_venv"
#          volttron_home: "{{ ansible_env.HOME }}/.volttron"
#          volttron_root: "{{ ansible_env.HOME }}/volttron"
#          volttron_venv: "{{ ansible_env.HOME }}/volttron.venv"
#          volttron_log_directory: "{{ ansible_env.HOME }}/logs"
#          host_configs_dir: "{{ ansible_env.HOME }}/configs"
  vars:
    volttron_features:
      - drivers
      - postgres
    deployment_platform_config_dir: "{{ inventory_dir }}/agent_configs"
    deployment_host_config_dir: "{{ inventory_dir }}/host_vars"
    ssh_key_file: ~/.ssh/
    generator_reports_dir: ~/generator_reports
    make_volttron_service: yes
    use_rotating_log: yes
    volttron_git_branch: develop
#    verbose_debug_tasks: yes
