---
- name: Generate ILC Generator Config
  ansible.builtin.template:
    src: ilc_generator_config.j2
    dest: "{{ host_configs_dir }}/ilc_generator_config.json"

- name: Run ILC Generator
  ansible.builtin.shell:
    cmd: "{{ venv_for_ansible }}/bin/volttron-config-gen {{ semantic_data.model_name }}
            {{ semantic_data.data_store_type }} ilc {{ host_configs_dir }}/ilc_generator_config.json"
  register: generator_return
  failed_when: generator_return.rc < 0 or generator_return.rc > 1

- name: Report Generator Errors
  ansible.builtin.copy:
    dest: ilc_issues.json
    content: "{{ generator_return.stderr }}"
  when: generator_return.rc | default('') == 1

- name: Fetch Generator Error Report
  ansible.builtin.fetch:
    dest: "{{ generator_reports_dir }}/{{ inventory_hostname }}/ilc_issues.json"
    src: "{{ host_configs_dir }}/ilc/errors/unmapped_device_details" # ilc_issues.json
    flat: yes
  when: (generator_return.rc is defined and generator_return.rc == 1)

- name: Install ILC Configs
  ansible.builtin.shell:
    cmd: "{{ volttron_venv }}/bin/vcfg --vhome {{ volttron_home }} update-config-store --metadata-file configs/ilc"

- name: Install ILC Dependencies
  ansible.builtin.pip:
    name:
      - sympy
      - transitions
    executable: "{{ volttron_venv }}/bin/pip"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Clone ILC
  ansible.builtin.git:
    repo: "{{ ilc_repo_url }}"
    version: "{{ ilc_git_branch }}"
    dest: volttron-ilc
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Clone Lighting Actuator
  ansible.builtin.git:
    repo: https://github.com/rlutes/volttron-lighting-actuator
    version: main
    dest: volttron-lighting-actuator
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  when: volttron_lighting_actuator_repo is defined

- name: Setup Agent Install
  set_fact:
    agents_to_install: "{{ 
    agents_to_install | default({}) | combine({ agent_vip : config_dict })
    }}"
  vars:
    config_dict:
      agent_source: "{{ ansible_env.HOME }}/volttron-ilc"
      agent_state: 'present'
      agent_enabled: True
      agent_priority: 50
      agent_running: True
      agent_tag: ilc
      skip_requirements: False
      force_install: False
    agent_vip: "{{ driver_generator.ilc_agent_vip | default('agent.ilc') }}"
