---
- name: Generate Economizer RCx Generator Config
  ansible.builtin.template:
    src: economizer_rcx_generator_config.j2
    dest: "{{ host_configs_dir }}/economizer_rcx_generator_config.json"

- name: Run Economizer RCx Generator
  ansible.builtin.shell:
    cmd: "{{ venv_for_ansible }}/bin/volttron-config-gen {{ semantic_data.model_name }}
            {{ semantic_data.data_store_type }} economizer {{ host_configs_dir }}/economizer_rcx_generator_config.json"
  register: generator_return
  failed_when: generator_return.rc < 0 or generator_return.rc > 1

- name: Report Generator Errors
  ansible.builtin.copy:
    dest: economizer_rcx_issues.json
    content: "{{ generator_return.stderr }}"
  when: generator_return.rc | default('') == 1

- name: Fetch Generator Error Report
  ansible.builtin.fetch:
    dest: "{{ generator_reports_dir }}/{{ inventory_hostname }}/economizer_rcx_issues.json"
    src: "{{ host_configs_dir }}/economizer_rcx/errors/unmapped_device_details" # economizer_rcx_issues.json
    flat: yes
  when: (generator_return.rc is defined and generator_return.rc == 1)

- name: Find Generated Files
  ansible.builtin.find:
    paths: "{{ host_configs_dir }}/economizer_rcx/configs"
    excludes: "unmapped_device_details"
  register: economizer_rcx_configs

- name: Load VOLTTRON Economizer RCx Configurations
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  register: economizer_rcx_config_set
  loop: "{{ economizer_rcx_configs.files }}"

- name: Install Economizer RCx Config
  ansible.builtin.shell:
    cmd: "{{ volttron_venv }}/bin/vcfg --vhome {{ volttron_home }} update-config-store --metadata-file configs/economizer_rcx"

- name: Clone Economizer RCx
  ansible.builtin.git:
    repo: "{{ economizer_repo_url  | default('git+https://github.com/eclipse-volttron/volttron-economizer-rcx') }}"
    version: "{{ economizer_git_branch  | default('main') }}"
    dest: volttron-economizer-rcx
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: Setup Agent Installs
  set_fact:
    agents_to_install: "{{ 
    agents_to_install | default({}) | combine({ agent_vip_prefix + '.' + ( item.device.unit | dict2items | map(attribute='key') | first ) : config_dict })
    }}"
  loop: "{{ economizer_rcx_config_set.results | map(attribute='content') | map('b64decode') | map('from_json') }}"
  vars:
    config_dict:
      agent_source: '{{ ansible_env.HOME }}/volttron-economizer-rcx'
      agent_state: 'present'
      agent_enabled: True
      agent_priority: 50
      agent_running: true
      agent_tag: 'rcx'
      skip_requirements: False
      force_install: False
    agent_vip_prefix: "{{ economizer_rcx_generator.agent_vip_prefix | default('economizer') }}"
